# Delivered by Post: The Synthetic Cannabis Flood in German Prisons

Author: Ciara Cesaro-Tadic <br>
Date: June 2026

## Focus 
Analyze the data from individual prisons and departments of justice and identify patterns. The focus is primarily on how the use of NPS has changed in recent years (both frequency and patterns of use).

## Import libraries

In [1]:
import pandas as pd
import os

print("Import successfull")

Import successfull

In [2]:
# Get Working direction 
print(os.getcwd())

/Users/ciara/Desktop/Lede_program/Projects/Penal_system/drug_smuggling

## Import data 
- In Germany, there is no database or statistical data on how many drugs are seized in individual prisons. That is why I sent individual inquiries to the prisons and the ministries of justice. In response, I received (as was, unfortunately, to be expected) data using different categories and methods of recording. I tried to standardize this data and compiled it in [this](https://docs.google.com/spreadsheets/d/1v_Z6_Yo5pwTfdltqMbvWKiJG01NzKQtMM7ACT-vNXIY/edit?gid=324394083#gid=324394083) Excel spreadsheet.

In [3]:
df = pd.read_excel("data/penal_system.xlsx", sheet_name="festgestelle_drogen_menge")
df

,Jahr,JVA,Bundesland,Cannabinoide_g,Kokain_g,Heroin_g,Spice_g,Ecstasy_stck,Subutex_stck,Subutex_g,Amphetamin_g,NPS_Papier_Konsumeinheiten_stck,NPS_Reinsubstanz_ml,NPS_Mischung_g,NPS_cm2,Tilidin_g
0,2019,Billwerder,Hamburg,356.46,6.06,0.10,9.74,0.0,150.50,NaN,16.21,NaN,NaN,NaN,NaN,NaN
1,2020,Billwerder,Hamburg,177.10,12.00,0.70,186.70,0.0,51.15,NaN,0.51,NaN,NaN,NaN,NaN,NaN
2,2021,Billwerder,Hamburg,348.50,12.80,1.00,38.90,0.0,33.00,NaN,10.60,NaN,NaN,NaN,NaN,NaN
3,2022,Billwerder,Hamburg,435.00,16.10,0.00,1.10,20.8,0.00,NaN,0.00,NaN,NaN,NaN,NaN,NaN
4,2023,Billwerder,Hamburg,263.00,0.00,0.00,12.00,95.0,27.40,NaN,38.70,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2021,NaN,Berlin,6510.97,139.71,128.45,NaN,NaN,NaN,466.27,961.93,NaN,NaN,19.72,NaN,208.12
62,2022,NaN,Berlin,10663.39,193.77,62.16,NaN,NaN,NaN,375.63,216.95,NaN,NaN,36.38,NaN,115.63
63,2023,NaN,Berlin,10954.21,362.24,19.22,NaN,NaN,NaN,395.30,426.14,NaN,NaN,440.61,NaN,220.33
64,2024,NaN,Berlin,12629.37,497.12,11.37,NaN,NaN,NaN,377.03,290.25,NaN,NaN,503.77,NaN,351.10
65,2025,NaN,Berlin,7623.48,822.76,76.96,NaN,NaN,NaN,84.88,181.78,NaN,NaN,2475.22,NaN,95.39

## Clean data

#### Check data types

In [4]:
df.dtypes;

#### Create new column "Spice_NPS_g"
- The columns “Spice_g” and “NPS_Mischung_g” capture the same information in the dataset, but for different time periods—presumably due to a renaming of the data category (‘Spice_g’ through 2023, “NPS_Mischung_g” starting in 2024). Since the two columns never overlap (no prison year has a value in both at the same time), they can be merged into a continuous time series without any loss of information.

In [5]:
df["NPS_Mischung_g"] = df["Spice_g"].combine_first(df["NPS_Mischung_g"])
df;

#### Select only specific columns

In [6]:
df_NPS = df[["Jahr", "JVA", "Bundesland", "NPS_Papier_Konsumeinheiten_stck", "NPS_Reinsubstanz_ml", "NPS_Mischung_g", "NPS_cm2", ]]
df_NPS;

#### Export dataframe

In [7]:
# df_NPS.to_excel("results/df_NPS.xlsx", index=False)

## Focus: Baden Württemberg

#### Filter by state Baden-Württemberg

In [8]:
df_NPS_BaWue = df_NPS[df_NPS['Bundesland'] == 'Baden Württemberg']
df_NPS_BaWue;

#### Select only specific columns

In [9]:
df_NPS_BaWue = df_NPS_BaWue[["Jahr", "NPS_cm2"]]
df_NPS_BaWue;

#### Drop NAs

In [10]:
df_NPS_BaWue = df_NPS_BaWue.dropna(subset=["NPS_cm2"])
df_NPS_BaWue;

#### Export dataframe

In [11]:
# df_NPS_BaWue.to_excel("results/df_NPS_BaWue.xlsx", index=False)

## Focus: Berlin

#### Filter by state Berlin

In [12]:
df_NPS_Berlin = df_NPS[df_NPS['Bundesland'] == 'Berlin']
df_NPS_Berlin

,Jahr,JVA,Bundesland,NPS_Papier_Konsumeinheiten_stck,NPS_Reinsubstanz_ml,NPS_Mischung_g,NPS_cm2
58,2018,NaN,Berlin,NaN,NaN,237.93,NaN
59,2019,NaN,Berlin,NaN,NaN,109.54,NaN
60,2020,NaN,Berlin,NaN,NaN,68.39,NaN
61,2021,NaN,Berlin,NaN,NaN,19.72,NaN
62,2022,NaN,Berlin,NaN,NaN,36.38,NaN
63,2023,NaN,Berlin,NaN,NaN,440.61,NaN
64,2024,NaN,Berlin,NaN,NaN,503.77,NaN
65,2025,NaN,Berlin,NaN,NaN,2475.22,NaN

#### Select only specific columns

In [13]:
df_NPS_Berlin = df_NPS_Berlin[["Jahr", "NPS_Mischung_g"]]
df_NPS_Berlin;

#### Export dataframe

In [14]:
df_NPS_Berlin.to_excel("results/df_NPS_Berlin.xlsx", index=False)

## Focus: Hamburg

#### Filter by state Baden-Württemberg

In [15]:
df_NPS_HH = df_NPS[df_NPS['Bundesland'] == 'Hamburg']
df_NPS_HH;

#### Group by state (not by individual correctional facilities)

In [16]:
df_NPS_HH_grouped = (
    df_NPS_HH.groupby("Jahr")[["NPS_Mischung_g", "NPS_Papier_Konsumeinheiten_stck"]]
    .sum()
    .reset_index()
)
df_NPS_HH_grouped

   Jahr  NPS_Mischung_g  NPS_Papier_Konsumeinheiten_stck
0  2019           67.26                              0.0
1  2020          267.94                              0.0
2  2021          504.46                              0.0
3  2022          105.20                              0.0
4  2023          203.61                              0.0
5  2024          114.66                          11306.5
6  2025           65.06                          11735.0
7  2026           54.64                           1872.0

#### Adding trend line for the devolopment of NPS_Mischung_g"

In [20]:
import numpy as np
x = df_NPS_HH_grouped["Jahr"]
y = df_NPS_HH_grouped["NPS_Mischung_g"]
steigung, achsenabschnitt = np.polyfit(x, y, 1)
df_NPS_HH_grouped["Trend_Mischung_g"] = steigung * x + achsenabschnitt
df_NPS_HH_grouped

   Jahr  NPS_Mischung_g  NPS_Papier_Konsumeinheiten_stck  Trend_Mischung_g
0  2019       67.260000                         0.000000        255.038114
1  2020      267.940000                         0.000000        233.354236
2  2021      504.460000                         0.000000        211.670357
3  2022      105.200000                         0.000000        189.986479
4  2023      203.610000                         0.000000        168.302600
5  2024      114.660000                     11306.500000        146.618722
6  2025       65.060000                     11735.000000        124.934843
7  2026      104.966316                      3596.210526        103.250965

#### Calculate Projection for the Year 2026

In [21]:
faktor = 365 / 190
maske = df_NPS_HH_grouped["Jahr"] == 2026

df_NPS_HH_grouped.loc[maske, "NPS_Mischung_g"] *= faktor
df_NPS_HH_grouped.loc[maske, "NPS_Papier_Konsumeinheiten_stck"] *= faktor
df_NPS_HH_grouped

   Jahr  NPS_Mischung_g  NPS_Papier_Konsumeinheiten_stck  Trend_Mischung_g
0  2019       67.260000                         0.000000        255.038114
1  2020      267.940000                         0.000000        233.354236
2  2021      504.460000                         0.000000        211.670357
3  2022      105.200000                         0.000000        189.986479
4  2023      203.610000                         0.000000        168.302600
5  2024      114.660000                     11306.500000        146.618722
6  2025       65.060000                     11735.000000        124.934843
7  2026      201.645817                      6908.509695        103.250965

#### Export dataframe

In [22]:
df_NPS_HH_grouped.to_excel("results/df_NPS_HH_grouped_trend.xlsx", index=False)

## Focus: Individual Correctional Facilities in Hamburg

#### Pivot in wide format

In [30]:
# pivot column "NPS_Papier_Konsumeinheiten_stck"
df_NPS_HH_pivot_1 = df_NPS_HH.pivot(index="Jahr", columns="JVA", values="NPS_Papier_Konsumeinheiten_stck").reset_index()
df_NPS_HH_pivot_1

JVA,Jahr,Billwerder,Fuhlsbüttel,Glasmoor,Hahnöfersand,Sozialtherapeutische Anstalt,Untersuchungshaftanstalt
0,2019,NaN,NaN,NaN,NaN,NaN,NaN
1,2020,NaN,NaN,NaN,NaN,NaN,NaN
2,2021,NaN,NaN,NaN,NaN,NaN,NaN
3,2022,NaN,NaN,NaN,NaN,NaN,NaN
4,2023,NaN,NaN,NaN,NaN,NaN,NaN
5,2024,3765.0,6164.5,0.0,0.0,1377.0,0.0
6,2025,151.5,11553.5,0.0,30.0,0.0,0.0
7,2026,140.0,1581.0,0.0,0.0,146.0,5.0

In [31]:
# pivot column "NPS_Papier_Konsumeinheiten_stck"
df_NPS_HH_pivot_2 = df_NPS_HH.pivot(index="Jahr", columns="JVA", values="NPS_Mischung_g").reset_index()
df_NPS_HH_pivot_2

JVA,Jahr,Billwerder,Fuhlsbüttel,Glasmoor,Hahnöfersand,Sozialtherapeutische Anstalt,Untersuchungshaftanstalt
0,2019,9.74,13.97,2.80,0.4,34.8,5.55
1,2020,186.70,67.25,0.00,0.0,13.8,0.19
2,2021,38.90,369.86,0.00,0.0,95.7,0.00
3,2022,1.10,57.40,0.00,0.0,46.7,0.00
4,2023,12.00,166.91,0.00,0.0,24.7,0.00
5,2024,0.00,109.76,0.00,0.0,4.9,0.00
6,2025,1.00,40.16,21.40,0.0,0.0,2.50
7,2026,0.40,18.10,34.94,0.0,1.2,0.00

#### Export dataframe

In [32]:
df_NPS_HH_pivot_1.to_excel("results/df_NPS_HH_pivot_1.xlsx", index=False)
df_NPS_HH_pivot_2.to_excel("results/df_NPS_HH_pivot_2.xlsx", index=False)